# Generated by Django 4.2.7 on 2025-12-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del curso')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('nivel', models.CharField(choices=[('BASICA', 'Educación Básica'), ('MEDIA', 'Educación Media'), ('SUPERIOR', 'Educación Superior')], default='BASICA', max_length=10, verbose_name='Nivel')),
                ('ano', models.IntegerField(verbose_name='Año')),
                ('capacidad_maxima', models.IntegerField(default=30, verbose_name='Capacidad máxima')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['ano', 'nombre'],
            },
        ),
    ]
