# Generated by Django 4.2.7 on 2025-12-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorCursos', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['nombre'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterField(
            model_name='curso',
            name='ano',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='capacidad_maxima',
            field=models.IntegerField(blank=True, default=30, verbose_name='Capacidad máxima'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(blank=True, choices=[('BASICA', 'Educación Básica'), ('MEDIA', 'Educación Media'), ('SUPERIOR', 'Educación Superior')], default='BASICA', max_length=10, verbose_name='Nivel'),
        ),
    ]
